name: Auto filter VLESS list
permissions:
  contents: write
on:
   schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  filter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download original list
        run: |
          curl -L https://raw.githubusercontent.com/zieng2/wl/main/vless_lite.txt -o source.txt

      - name: Remove unwanted countries
        run: |
          grep -v -E "üá∑üá∫|RU|cloud\.ru|Yandex|VK|Beget|Baxet|masterhost|Selectel|Timeweb|Moscow|MSK|üá®üá≥|CN|üáÆüá∑|IR" source.txt > filtered.txt
      - name: Save result
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          # –ü–æ–¥—Ç—è–Ω—É—Ç—å –∞–∫—Ç—É–∞–ª—å–Ω—ã–π main –∏ ‚Äú–ø–æ—Å—Ç–∞–≤–∏—Ç—å —Å–µ–±—è‚Äù –ø–æ–≤–µ—Ä—Ö –Ω–µ–≥–æ
          git fetch origin main
          git checkout main
          git reset --hard origin/main

          # –ó–∞–ø–∏—Å–∞—Ç—å –Ω–æ–≤—ã–π filtered.txt (–æ–Ω —É–∂–µ —Å–æ–∑–¥–∞–Ω –Ω–∞ –ø—Ä–µ–¥—ã–¥—É—â–µ–º —à–∞–≥–µ)
          git add filtered.txt
          git commit -m "auto update filtered list" || true

          # –ü—É—à–∏–º –ø–æ–≤–µ—Ä—Ö, —á—Ç–æ–±—ã –Ω–µ –±—ã–ª–æ fetch-first –∫–æ–Ω—Ñ–ª–∏–∫—Ç–æ–≤
          git push --force origin main
