name: Auto filter VLESS list

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  filter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download original list
        run: |
          curl -L https://raw.githubusercontent.com/zieng2/wl/main/vless_lite.txt -o source.txt

      - name: Remove unwanted countries
        run: |
          grep -v -E "üá∑üá∫|RU|cloud\.ru|Yandex|VK|Beget|Baxet|masterhost|Selectel|Timeweb|Moscow|MSK|üá®üá≥|CN|üáÆüá∑|IR" source.txt > filtered.txt
      - name: Save result
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          # –í—Å–µ–≥–¥–∞ —Ä–∞–±–æ—Ç–∞–µ–º —Å –∞–∫—Ç—É–∞–ª—å–Ω—ã–º main
          git fetch origin main
          git reset --hard origin/main

          # –ö–ª–∞–¥—ë–º –Ω–æ–≤—ã–π filtered.txt
          mv filtered.txt filtered.txt

          git add filtered.txt
          git commit -m "auto update filtered list" || true
          git push --force origin HEAD:main
